name: Defold-builder-simple
description: Create archives using Defold's Bob the Builder. PRs to extend/improve accepted.
author: 'prismglue'
icon: 'truck'
color: 'green'

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      branch:
        description: ""
        required: true
        default: "main"
      settings:
        description: "bob settings file (e.g. 'prod.ini')"
        required: false
        default: ""

env:
  DEFOLD_VERSION: '1.8.0'
  BUILD_SERVER: https://build.defold.com
  PROJECT_TITLE: ""         # Bob uses game.project as part of the build output path
  PLATFORM: 'js-web'
  ARCHITECTURES: 'wasm-web' # Swap back to js-web,wasm-web for maximum compatibility
  GITHUB_ARCHIVE: true

jobs:
  environ:
    name: Extract environment variables for use within a build (GitHub Actions has some interesting restrictions)
    runs-on: ubuntu-latest
    outputs:
      DEFOLD_VERSION: ${{ env.DEFOLD_VERSION }}
      PLATFORM: ${{ env.PLATFORM }}
      ARCHITECTURES: ${{ env.ARCHITECTURES }}
      BUILD_SERVER: ${{ env.BUILD_SERVER }}
      PROJECT_TITLE: ${{ env.PROJECT_TITLE }}
      GITHUB_ARCHIVE: ${{ env.GITHUB_ARCHIVE }}
  build:
    name: Build 
    runs-on: ubuntu-latest
    # defaults: # You might have to do this yourself...
    #   run:
    #     working-directory: ${{ env.GAME_DIRECTORY }}
    steps:
      - uses: actions/setup-java@v2
        with:
          java-version: '17'      # Feel free to bump this or argue for another distribution - it can't be extracted to env: for mutability reasons
          distribution: 'temurin'

      - name: Download bob.jar # Being kind to Defold by using GitHub's bandwidth (Android+iOS builder uses an S3 bucket Defold seems to maintain)
        run: |
          wget -q https://github.com/defold/defold/releases/download/${{needs.environ.outputs.DEFOLD_VERSION}}/bob.jar
          java -jar bob.jar --version

      - name: Apply extra bob flags
        id: bob-flags
        run: |
          FLAGS+=$([[ '${{ github.event.inputs.settings }}' ]] && echo ' --settings ${{ github.event.inputs.settings }}' || echo)
          echo "::set-output name=flags::$FLAGS"

      - name: Resolve libraries
        run: java -jar bob.jar resolve

      - name: Build
        run: java -jar bob.jar --platform=${{ needs.environ.outputs.PLATFORM }} --architectures=${{needs.environ.outputs.ARCHITECTURES}} build --archive --build-server=${{ needs.environ.outputs.BUILD_SERVER }}

      - name: Bundle
        run: java -jar bob.jar --platform=${{ needs.environ.outputs.PLATFORM }} --architectures=${{needs.environ.outputs.ARCHITECTURES}} ${{ steps.bob-flags.outputs.flags }} bundle
        
      - name: Show output
        run: |
          ls -l build
          ls -l build/default
          ls -l build/default/${{needs.environ.outputs.PROJECT_TITLE}}

      - name: Get short commit sha
        id: short-commit-sha
        run: echo "::set-output name=sha::$(git rev-parse --short ${{ github.sha }})"

      - uses: actions/upload-artifact@v4
        if: '${{needs.environ.outputs.GITHUB_ARCHIVE}}'
        with:
          compression-level: 9
          name: ${{ needs.environ.outputs.PLATFORM }}_commit_${{ steps.short-commit-sha.outputs.sha }}
          path: build/default/${{needs.environ.outputs.PROJECT_TITLE}}/
