name: Defold-builder-simple
description: Create archives using Defold's Bob the Builder. PRs to extend/improve accepted.
author: 'prismglue'
icon: 'truck'
color: 'green'

on:
  workflow_call:
    inputs:
      PROJECT_TITLE:
        description: 'Project title (inside game.project - Bob uses game.project as part of the build output path)'
        required: true
        type: string
      DEFOLD_VERSION:
        description: "Version of Defold to use for builds"
        required: false
        type: string
        default: '1.8.0'
      BUILD_SERVER:
        required: false
        description: "Custom build server"
        type: string
        default: 'https://build.defold.com'
      PLATFORM:
        type: string
        default: 'js-web'
        required: false
        description: 'Bob build platform'
      ARCHIVE:
        type: boolean
        default: true
        required: false
        description: 'Archive output to GitHub'
      ARCHITECTURES:
        type: string
        default: 'wasm-web'
        required: false
        description: 'Bob build architectures (Swap back to js-web,wasm-web for maximum compatibility)'
  workflow_dispatch: # Yep. This is required. If you remove it, it breaks workflow_dispatch. If you remove workflow_call, it breaks default builds. Zany...
    inputs:
      PROJECT_TITLE:
        description: 'Project title (inside game.project - Bob uses game.project as part of the build output path)'
        required: true
        type: string
      DEFOLD_VERSION:
        description: "Version of Defold to use for builds"
        required: false
        type: string
        default: '1.8.0'
      BUILD_SERVER:
        required: false
        description: "Custom build server"
        type: string
        default: 'https://build.defold.com'
      PLATFORM:
        type: string
        default: 'js-web'
        required: false
        description: 'Bob build platform'
      ARCHIVE:
        type: boolean
        default: true
        required: false
        description: 'Archive output to GitHub'
      ARCHITECTURES:
        type: string
        default: 'wasm-web'
        required: false
        description: 'Bob build architectures (Swap back to js-web,wasm-web for maximum compatibility)'

jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    # defaults: # You might have to do this yourself...
    #   run:
    #     working-directory: ${{ inputs.GAME_DIRECTORY }}
    steps:
      - uses: actions/setup-java@v2
        with:
          java-version: '17'      # Feel free to bump this or argue for another distribution - it can't be extracted to env: for mutability reasons
          distribution: 'temurin'

      - name: Download bob.jar # Being kind to Defold by using GitHub's bandwidth (Android+iOS builder uses an S3 bucket Defold seems to maintain)
        run: |
          wget -q https://github.com/defold/defold/releases/download/${{github.event.inputs.DEFOLD_VERSION}}/bob.jar
          java -jar bob.jar --version

      # - name: Apply extra bob flags
      #   id: bob-flags
      #   run: |
      #     FLAGS+=$([[ '${{ github.event.inputs.settings }}' ]] && echo ' --settings ${{ github.event.inputs.settings }}' || echo)
      #     echo "::set-output name=flags::$FLAGS"

      - name: Resolve libraries
        run: java -jar bob.jar resolve

      - name: Build
        run: java -jar bob.jar --platform=${{ github.event.inputs.PLATFORM }} --architectures=${{github.event.inputs.ARCHITECTURES}} build --archive --build-server=${{ github.event.inputs.BUILD_SERVER }}

      - name: Bundle
        run: java -jar bob.jar --platform=${{ github.event.inputs.PLATFORM }} --architectures=${{github.event.inputs.ARCHITECTURES}} ${{ steps.bob-flags.outputs.flags }} bundle
        
      - name: Show output
        run: |
          ls -l build
          ls -l build/default
          ls -l build/default/${{github.event.inputs.PROJECT_TITLE}}

      - name: Get short commit sha
        id: short-commit-sha
        run: echo "::set-output name=sha::$(git rev-parse --short ${{ github.sha }})"

      - uses: actions/upload-artifact@v4
        if: '${{github.event.inputs.ARCHIVE}}'
        with:
          compression-level: 9
          name: ${{ github.event.inputs.PLATFORM }}_commit_${{ steps.short-commit-sha.outputs.sha }}
          path: build/default/${{github.event.inputs.PROJECT_TITLE}}/
